Updated CDP.py
ultrafunkamsterdam/undetected-chromedriver pull request #294
Opened 2021-09-03 13:58 UTC by Duckylol

`collections.abc` houses the legacy classes _Mapping_ and _Sequence_

This fixes the `cannot import name 'Mapping' from 'collections'`  bug.

![image](https://user-images.githubusercontent.com/74636869/132017290-e50d48f8-1a42-4158-a291-84550bc5a9e0.png)

2021-11-12 06:12 UTC, FastestMolasses commented
@Duckylol Can you update this to remove that line entirely? Mapping or Sequence is not used in the code and your change will allow this repo to be backward compatible still.

@ultrafunkamsterdam

2021-12-08 11:02 UTC, Lovelaces requested changes
'''
import sys
import json
import logging
exec('from collections.abc import Mapping, Sequence') if sys.version_info >= (3, 3) else exec('from collections import Mapping, Sequence')
'''
This should help with forward and backward compatibility! I felt quite proud coming up with it :)

2021-12-08 11:02 UTC, Lovelaces commented on undetected_chromedriver/cdp.py
> +from collections.abc import Mapping, Sequence
```suggestion
import sys
import json
import logging
exec('from collections.abc import Mapping, Sequence') if sys.version_info >= (3, 3) else exec('from collections import Mapping, Sequence')
```
This should help with forward and backward compatibility! Felt a bit proud coming up with a pythonic ternary operator :)

2022-07-14 10:02 UTC, ultrafunkamsterdam commented
thanks! meanwhile this has been resolved some time ago.

2022-07-14 10:02 UTC, closed without merging